-   id: inaxs
    name: inaxs
    description: "Lint common markdown files for accessibility errors."
    entry: inaxs
    language: python
    language_version: python3
    types: [python]
    require_serial: true
